export default {
  add_new_image: require('../assets/add_new_image.png'),
  search: require('../assets/search.png'),
  gojobg: require('../assets/gojobg.jpg'),
  bell: require('../assets/bell.png'),
  login: require('../assets/login.png'),
  user: require('../assets/user.png'),
  choseimage: require('../assets/choseimage.png'),
  meme: require('../assets/meme.png'),
  myimage: require('../assets/myimage.png'),
  videotogit: require('../assets/videotogit.png'),
  close: require('../assets/close.png'),
  thu: require('../assets/thu.png'),
  eyes: require('../assets/eyes.png'),
  love: require('../assets/love.png'),
  chat: require('../assets/chat.png'),
  imgOpenBook: require('../assets/img_open_book.png'),
}
