export const languages = [
  {value: 'af', label: 'Afrikaans'},
  {value: 'ale', label: 'Aleut'},
  {value: 'ar', label: 'Arabic'},
  {value: 'arp', label: 'Arapaho'},
  {value: 'brx', label: 'Bodo'},
  {value: 'br', label: 'Breton'},
  {value: 'bg', label: 'Bulgarian'},
  {value: 'rmq', label: 'Caló'},
  {value: 'ca', label: 'Catalan'},
  {value: 'ceb', label: 'Cebuano'},
  {value: 'zh', label: 'Chinese'},
  {value: 'cs', label: 'Czech'},
  {value: 'da', label: 'Danish'},
  {value: 'nl', label: 'Dutch'},
  {value: 'en', label: 'English'},
  {value: 'eo', label: 'Esperanto'},
  {value: 'et', label: 'Estonian'},
  {value: 'fa', label: 'Farsi'},
  {value: 'fi', label: 'Finnish'},
  {value: 'fr', label: 'French'},
  {value: 'fy', label: 'Frisian'},
  {value: 'fur', label: 'Friulian'},
  {value: 'gla', label: 'Gaelic, Scottish'},
  {value: 'gl', label: 'Galician'},
  {value: 'kld', label: 'Gamilaraay'},
  {value: 'de', label: 'German'},
  {value: 'el', label: 'Greek'},
  {value: 'grc', label: 'Greek, Ancient'},
  {value: 'he', label: 'Hebrew'},
  {value: 'hu', label: 'Hungarian'},
  {value: 'is', label: 'Icelandic'},
  {value: 'ilo', label: 'Iloko'},
  {value: 'ia', label: 'Interlingua'},
  {value: 'iu', label: 'Inuktitut'},
  {value: 'ga', label: 'Irish'},
  {value: 'it', label: 'Italian'},
  {value: 'ja', label: 'Japanese'},
  {value: 'csb', label: 'Kashubian'},
  {value: 'kha', label: 'Khasi'},
  {value: 'ko', label: 'Korean'},
  {value: 'la', label: 'Latin'},
  {value: 'lt', label: 'Lithuanian'},
  {value: 'mi', label: 'Maori'},
  {value: 'myn', label: 'Mayan Languages'},
  {value: 'enm', label: 'Middle English'},
  {value: 'nah', label: 'Nahuatl'},
  {value: 'nap', label: 'Napoletano-Calabrese'},
  {value: 'nav', label: 'Navajo'},
  {value: 'nai', label: 'North American Indian'},
  {value: 'no', label: 'Norwegian'},
  {value: 'oc', label: 'Occitan'},
  {value: 'oji', label: 'Ojibwa'},
  {value: 'ang', label: 'Old English'},
  {value: 'pl', label: 'Polish'},
  {value: 'pt', label: 'Portuguese'},
  {value: 'ro', label: 'Romanian'},
  {value: 'ru', label: 'Russian'},
  {value: 'sa', label: 'Sanskrit'},
  {value: 'sr', label: 'Serbian'},
  {value: 'sl', label: 'Slovenian'},
  {value: 'es', label: 'Spanish'},
  {value: 'sv', label: 'Swedish'},
  {value: 'bgs', label: 'Tagabawa'},
  {value: 'tl', label: 'Tagalog'},
  {value: 'te', label: 'Telugu'},
  {value: 'cy', label: 'Welsh'},
  {value: 'yi', label: 'Yiddish'},
]

export const subjects = [
  {
    label: 'Adventure',
    value: 'Adventure stories',
  },
  {
    label: 'Biography & Autobiography',
    value: 'Biography & Autobiography',
  },
  {
    label: "Children's Literature",
    value: "Children's stories",
  },
  {
    label: 'Classic Literature',
    value: 'Classic Literature',
  },
  {
    label: 'Detective Fiction',
    value: 'Detective fiction',
  },
  {
    label: 'Drama',
    value: 'Drama',
  },
  {
    label: 'Epic Poetry',
    value: 'Epic poetry',
  },
  {
    label: 'Essays',
    value: 'Essays',
  },
  {
    label: 'Fairy Tales',
    value: 'Fairy tales',
  },
  {
    label: 'Fantasy',
    value: 'Fantasy fiction',
  },
  {
    label: 'Folklore',
    value: 'Folklore',
  },
  {
    label: 'Gothic Fiction',
    value: 'Gothic fiction',
  },
  {
    label: 'Historical Fiction',
    value: 'Historical fiction',
  },
  {
    label: 'Horror',
    value: 'Horror tales',
  },
  {
    label: 'Humor',
    value: 'Humor',
  },
  {
    label: 'Letters',
    value: 'Letters',
  },
  {
    label: 'Literary Fiction',
    value: 'Literary fiction',
  },
  {
    label: 'Love Stories',
    value: 'Love stories',
  },
  {
    label: 'Mystery',
    value: 'Mystery fiction',
  },
  {
    label: 'Mythology',
    value: 'Mythology',
  },
  {
    label: 'Philosophy',
    value: 'Philosophy',
  },
  {
    label: 'Poetry',
    value: 'Poetry',
  },
  {
    label: 'Political Fiction',
    value: 'Political fiction',
  },
  {
    label: 'Religious Literature',
    value: 'Religious literature',
  },
  {
    label: 'Romance',
    value: 'Romance fiction',
  },
  {
    label: 'Satire',
    value: 'Satire',
  },
  {
    label: 'Science Fiction',
    value: 'Science fiction',
  },
  {
    label: 'Sea Stories',
    value: 'Sea stories',
  },
  {
    label: 'Short Stories',
    value: 'Short stories',
  },
  {
    label: 'War Stories',
    value: 'War stories',
  },
]
