export const listOptions = [
  {
    id: 1,
    url: 'https://i.imgur.com/JJ3tmg6.jpg',
    backgroundColor: '#9a84e9',
    title: 'Classical Literature',
    quantity: '1,200',
  },
  {
    id: 2,
    url: 'https://i.imgur.com/6Ebubdn.jpg',
    backgroundColor: '#02fb62',
    title: 'Science Fiction',
    quantity: '300',
  },
  {
    id: 3,
    url: 'https://i.imgur.com/W1tDyVO.jpg',
    backgroundColor: '#02eefb',
    title: 'Love stories',
    quantity: '881',
  },
  {
    id: 4,
    url: 'https://i.imgur.com/aqfzW8f.jpg',
    backgroundColor: '#ec9cbf',
    title: 'Historical Fiction',
    quantity: '3,300',
  },
  {
    id: 5,
    url: 'https://i.imgur.com/7tbj9o1.jpg',
    backgroundColor: '#4b27a5',
    title: 'Gothic Fiction',
    quantity: '558',
  },
  {
    id: 6,
    url: 'https://i.imgur.com/sdyyEH3.jpg',
    backgroundColor: '#791aae',
    title: 'Sea stories',
    quantity: '200',
  },
  {
    id: 7,
    url: 'https://i.imgur.com/VmNBNyt.png',
    backgroundColor: '#010059',
    title: 'Social life',
    quantity: '1,132',
  },
  {
    id: 8,
    url: 'https://i.imgur.com/DnjIfbk.jpg',
    backgroundColor: '#db98bb',
    title: 'Political Fiction',
    quantity: '159',
  },
  {
    id: 9,
    url: 'https://i.imgur.com/KFwJx7P.jpg',
    backgroundColor: '#121818',
    title: 'Adventure stories',
    quantity: '599',
  },
  {
    id: 10,
    url: 'https://i.imgur.com/9O6LHZ5.jpg',
    backgroundColor: '#9f82bd',
    title: 'Short stories',
    quantity: '300',
  },
]
